name: Deploy Fatal Error Website

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Run Linting
      run: npm run lint
      
    - name: Run Type Check
      run: npm run build
      continue-on-error: false
      
    - name: Build Next.js Application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Export Static Files
      run: npm run export
      continue-on-error: true
      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: |
          .next/
          out/
        retention-days: 30
        
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: fatal-error.dev  # Optional: Add your custom domain here
        
    # Optional: Deploy to Vercel (uncomment if you want Vercel deployment)
    # - name: Deploy to Vercel
    #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}
    #     working-directory: ./

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Run Security Audit
      run: npm audit --audit-level moderate
      continue-on-error: true
      
    - name: Run Dependency Check
      uses: actions/dependency-review-action@v4
      if: github.event_name == 'pull_request'
